### ISSUE TITLE
Bug : (Error 405 ) Not validating the user in vercel server but working in local machine

### ISSUE THREAD

**Issue by chandan24042001s** [chandan24042001s/Zummit#42]
Ticket- AM -1
Bug : (Error 405 ) Not validating the user in vercel server but working in local machine

Step to reproduce : 
    1. Go to https://zummit-chandan.vercel.app/api/users/login  . Try to login with given credentials
    2. Open network tab in console and relogin will throw back the 405 Error

Expeted results : Status 200 or 304 
Actual results : 405 unauthorized error.

![image](https://github.com/chandan24042001s/Zummit/assets/85206406/5a58d29e-cef2-486a-8fb0-c4366443d6cc)

**Comment by Vaibhav-Thalanki** [comment]
solved
